### ISSUE TITLE
Ubuntu 16.04 Xenial has strict(-er) package key requirements

### ISSUE THREAD

**Issue by PKRoma** [shaggytwodope/shaggytwodope.github.io#1]
Hi, thanks for your excellent service. I recently upgraded to Ubuntu 16.04 Xenial and trying to install 'drive' using apt-get gives me the following warnings and error on 'apt-get update'. Could you possibly upgrade to use stronger keys and hashes?

W: http://shaggytwodope.github.io/repo/./Release.gpg: Signature by key 8F1AD38DE8A08544A55129817086E9CC7EC3233B uses weak digest algorithm (SHA1)
E: Failed to fetch http://shaggytwodope.github.io/repo/./Release  No Hash entry in Release file /var/lib/apt/lists/partial/shaggytwodope.github.io_repo_._Release which is considered strong enough for security purposes
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by shaggytwodope** [comment]
@PKRoma I'm sorry that this happened. I've updated what I needed to fix this. Can you confirm it is working for you now?

**Comment by PKRoma** [comment]
Not a problem: Confirmed working and able to install 'drive' on Ubuntu 16.04 Xenial with no warnings or errors as in the original problem statement.

Thanks very much for your quick response!
