### ISSUE TITLE
github.io doesn't serves binary files stored with git LFS

### ISSUE THREAD

**Issue by DenJohX** [shaggytwodope/shaggytwodope.github.io#2]
Yup, this affects the debian repo as the downloaded files aren't the actual .deb files but the text references to them.

**Comment by shaggytwodope** [comment]
So I swear for the life of me I've removed LFS completely. But more over, I actively use the repo. Can you tell me what packages are doing this?

**Comment by shaggytwodope** [comment]
@DenJohX I've wiped the repo, and reinitialized everything. The files should be stored normally. If you can confirm and close the issue that'd be great. Thank you for reporting any issues.

**Comment by DenJohX** [comment]
@shaggytwodope I was having problems with the debian repo, but everythings seems to work now. Thanks!
